# ===============================
# SonarCloud - Angular 19
# ===============================

sonar.organization=TON_ORG_SONARCLOUD
sonar.projectKey=TON_ORG_SONARCLOUD_cocktails
sonar.projectName=cocktails
sonar.projectVersion=1.0

# Sources
sonar.sources=cocktails/src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

# Tests (optionnel si tu en ajoutes plus tard)
sonar.tests=cocktails/src
sonar.test.inclusions=**/*.spec.ts

# TypeScript
sonar.language=ts
sonar.sourceEncoding=UTF-8

# Coverage (à activer plus tard si tu ajoutes les tests)
# sonar.javascript.lcov.reportPaths=cocktails/coverage/lcov.info
